import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/wonder.dart';

/// The wonder catalog, loaded once from assets/wonders.json.
///
/// That asset is generated by `node scripts/export-wonders.js` from the
/// TypeScript catalog in ../../lib/wonders/, which stays the single source of
/// truth. Nothing here is hand-maintained; re-run the export after editing a
/// card.
///
/// 178 records is small enough to hold in memory and filter in Dart, which is
/// why this is a JSON asset and the Bible is a database.
class WondersRepository {
  WondersRepository._({
    required this.wonders,
    required this.themeLabels,
    required this.eraLabels,
    required this.eraOrder,
  })  : _byId = {for (final w in wonders) w.id: w},
        _byParallelGroup = _groupParallels(wonders);

  static const _assetPath = 'assets/wonders.json';

  /// The shape scripts/export-wonders.js writes. Refuse to parse anything
  /// newer rather than silently dropping fields.
  static const _supportedSchema = 1;

  final List<Wonder> wonders;
  final Map<WonderTheme, String> themeLabels;
  final Map<WonderEra, String> eraLabels;

  /// Reading order for the era filter.
  final List<WonderEra> eraOrder;

  final Map<String, Wonder> _byId;
  final Map<String, List<Wonder>> _byParallelGroup;

  static WondersRepository? _instance;

  static Future<WondersRepository> load() async {
    final existing = _instance;
    if (existing != null) return existing;

    final raw = await rootBundle.loadString(_assetPath);
    final json = jsonDecode(raw) as Map<String, dynamic>;

    final schema = (json['schemaVersion'] as num?)?.toInt() ?? 0;
    if (schema > _supportedSchema) {
      throw StateError(
        'assets/wonders.json is schema v$schema but this build understands '
        'v$_supportedSchema. Update lib/models/wonder.dart and bump '
        '_supportedSchema.',
      );
    }

    return _instance = WondersRepository._(
      wonders: (json['wonders'] as List<dynamic>)
          .map((e) => Wonder.fromJson(e as Map<String, dynamic>))
          .toList(),
      themeLabels: _labelMap(
        json['themeLabels'] as Map<String, dynamic>?,
        WonderTheme.parse,
      ),
      eraLabels: _labelMap(
        json['eraLabels'] as Map<String, dynamic>?,
        WonderEra.parse,
      ),
      eraOrder: (json['eraOrder'] as List<dynamic>?)
              ?.map((e) => WonderEra.parse(e as String))
              .toList() ??
          WonderEra.values,
    );
  }

  static Map<T, String> _labelMap<T>(
    Map<String, dynamic>? raw,
    T Function(String) parse,
  ) {
    if (raw == null) return {};
    return {
      for (final entry in raw.entries) parse(entry.key): entry.value as String,
    };
  }

  static Map<String, List<Wonder>> _groupParallels(List<Wonder> wonders) {
    final groups = <String, List<Wonder>>{};
    for (final w in wonders) {
      final group = w.parallelGroupId;
      if (group != null) groups.putIfAbsent(group, () => []).add(w);
    }
    return groups;
  }

  int get count => wonders.length;

  Wonder? byId(String id) => _byId[id];

  List<Wonder> get authored => wonders.where((w) => w.authored).toList();

  /// The other accounts of the same event — what "Also in Matthew · Luke"
  /// links to. Excludes [wonder] itself.
  List<Wonder> parallelsOf(Wonder wonder) {
    final group = wonder.parallelGroupId;
    if (group == null) return const [];
    return (_byParallelGroup[group] ?? const [])
        .where((w) => w.id != wonder.id)
        .toList();
  }

  /// Best-known first. Unranked wonders keep Bible order behind the ranked
  /// ones rather than being dropped.
  List<Wonder> byFamiliarity([List<Wonder>? source]) {
    final list = [...(source ?? wonders)];
    list.sort((a, b) {
      final ra = a.familiarityRank;
      final rb = b.familiarityRank;
      if (ra != null && rb != null) return ra.compareTo(rb);
      if (ra != null) return -1;
      if (rb != null) return 1;
      return 0;
    });
    return list;
  }

  /// The Start Here shortlist: the ranked wonders, best-known first.
  List<Wonder> startHere({int limit = 25}) =>
      byFamiliarity(wonders.where((w) => w.isRanked).toList()).take(limit).toList();

  List<Wonder> byTheme(WonderTheme theme) =>
      wonders.where((w) => w.theme == theme).toList();

  List<Wonder> byEra(WonderEra era) =>
      wonders.where((w) => w.era == era).toList();

  /// Eras that actually have wonders, in reading order — so the era picker
  /// never offers an empty filter.
  List<WonderEra> populatedEras() {
    final present = wonders.map((w) => w.era).toSet();
    return eraOrder.where(present.contains).toList();
  }

  /// Ranked search over the catalog, best match first.
  ///
  /// Three tiers, because each simpler design is wrong on its own. Names only
  /// — title, reference, place — misses every query for a person: no card is
  /// titled "Jesus", so searching for Him returned nothing at all. Prose
  /// included flat makes "sea" return every card that mentions one in passing,
  /// ahead of the sea crossings themselves. And scattered terms alone make
  /// "Exodus 14" match Exodus 7:14 just as well as Exodus 14, because
  /// normalising a reference leaves its numbers as loose words.
  ///
  /// So: the query as a phrase in the name, then all its terms in the name,
  /// then all its terms anywhere on the card. Bible order is preserved inside
  /// each tier. Multi-word queries are AND, which is what makes "jesus
  /// leprosy" narrow rather than widen.
  List<Wonder> search(String query) {
    final terms = _termsOf(query);
    if (terms.isEmpty) return const [];
    final phrase = terms.join(' ');

    final exact = <Wonder>[];
    final named = <Wonder>[];
    final prose = <Wonder>[];
    for (final w in wonders) {
      final name = _nameText(w);
      if (name.contains(phrase)) {
        exact.add(w);
      } else if (terms.every(name.contains)) {
        named.add(w);
      } else if (terms.every(_proseText(w).contains)) {
        prose.add(w);
      }
    }
    return [...exact, ...named, ...prose];
  }

  /// How many wonders the query matches anywhere in the catalog, ignoring the
  /// current path. The home screen needs this to tell "nothing matches" apart
  /// from "nothing matches *here*", which are very different dead ends.
  int matchCount(String query) => search(query).length;

  /// Title, reference, book and place — what a wonder is *called*.
  String _nameText(Wonder w) {
    return _nameCache[w.id] ??= _normalise(
      [w.title, w.passage.label, w.passage.bookName, w.location ?? ''].join(' '),
    );
  }

  /// Everything on the card, the name fields included, so a wonder that
  /// matches on both still only needs one tier to be checked first.
  String _proseText(Wonder w) {
    return _proseCache[w.id] ??= _normalise(
      [
        _nameText(w),
        w.quote ?? '',
        w.quoteRef ?? '',
        w.whatHappened ?? '',
        w.hopeMeaning ?? '',
        w.reflectionQuestion ?? '',
        w.distinctive ?? '',
        ...w.details,
      ].join(' '),
    );
  }

  final Map<String, String> _nameCache = {};
  final Map<String, String> _proseCache = {};

  static List<String> _termsOf(String query) =>
      _normalise(query).split(' ').where((t) => t.isNotEmpty).toList();

  /// The WEB text and the card titles disagree about apostrophe style, and the
  /// prose is full of em dashes, so fold those away and flatten whitespace
  /// before comparing.
  static String _normalise(String s) => s
      .toLowerCase()
      .replaceAll(RegExp(r"['’]"), '')
      .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
      .trim();

  String labelFor(WonderTheme theme) => themeLabels[theme] ?? theme.id;
  String labelForEra(WonderEra era) => eraLabels[era] ?? era.id;
}
